DROP TABLE IF EXISTS articles;
CREATE TABLE articles (
  id VARCHAR(32) PRIMARY KEY,
  author TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL
);
